### ISSUE TITLE
Headless browser request

### ISSUE THREAD

**Issue by spam8117** [tomreece/pucauto#1]
Hey!
Great idea, thanks for doing this :-)
I don't know where to put requests so I'm posting it here:

An essential option would be a minPoints value in order to not get trades with e.g. 20 points.
2nd request is support for headless browser so you could run this technically from a Linux shell without GUI (e.g. Raspberry Pi).

Thanks & Regards

**Comment by tomreece** [comment]
To avoid low point trades, I don't even keep cards on my have list that are less than 100 points.

Regarding your second question, I'll look in to it. The great thing about open source software is that you could modify the source and do that! :)

It should be as easy as downloading PhantomJS (http://phantomjs.org/) on your machine and changing the line in the source that says `driver = webdriver.Firefox()` to `driver = webdriver.PhantomJS()`

**Comment by tomreece** [comment]
I added an Advanced Usage section to the README which explains how to run pucauto on a Linux server like an AWS, Rackspace, or Linode instance. https://github.com/tomreece/pucauto#advanced-usage

I'm not sure if it would work on a Raspberry Pi in this style or not. Do you want to try it out? If it doesn't work, please reopen a new issue. Closing this one for now.

PS: I moved your minPoints request to a separate issue so that issues are single requests. Thanks.
