### ISSUE TITLE
Show trade preview before committing cards to trade

### ISSUE THREAD

**Issue by akeeton** [tomreece/pucauto#23]
For example, I ran pucauto and it committed a card that wasn't NM.  It would be nice to be able to double-check my cards before committing.

**Comment by twilightwolf90** [comment]
I would argue that, that is not the design of the bot.  It is designed to automatically accept trades. You aren't supposed to have non-NM cards on your list anyway because Pucatrade doesn't support it (yet!).  You might want to look at helper scripts like PucaPower instead of Pucauto.

For everyone else, I propose closing this issue with no changes.  Unless there is some way to show a preview and commit to the trade in a timely manner that does not lose the trade.

**Comment by akeeton** [comment]
I should mention that the card _was_ NM but I bungled it and made it not NM after it was committed.

**Comment by tomreece** [comment]
I can't do much about these situations. Be more careful. :)
