### ISSUE TITLE
Make easier to run for Windows users

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#30]
@droogans How do Windows users typically install dependencies that us Mac users would install with pip? I want them to be able to use my `requirements.txt` file not have to manually go grab every dependency I keep adding. I'm about to merge a PR that adds Six to the project. Thoughts?

**Comment by Droogans** [comment]
Don't add six -- just write it all in Python 3.

What dependency do you have that doesn't allow you to use Python 3?

**Comment by Droogans** [comment]
[Selenium supports 3.3](https://pypi.python.org/pypi/selenium)
[BeautifulSoup](http://www.crummy.com/software/BeautifulSoup/) just says "Python 3"

Other than that, you have no other dependencies. I think you shouldn't use six when you can just do it in Python 3.

**Comment by tomreece** [comment]
I use Python 2 myself and would like to support both versions or only Python 2. :stuck_out_tongue:

**Comment by XVicarious** [comment]
It is possible to distribute a binary compiled with py2exe or pyinstaller.  However that would require actually building it.

Also, does pip not come with python?  According to this: http://pip.readthedocs.org/en/stable/installing/ it has since 2.7.9, and 3.4.  So unless you're running an older vesion of Python you should be set.  You just have to run it as so

```
python -m pip install -r requirements.txt
```

I'm working on confirming this on my virtual machine with Windows now.

EDIT:  Apparently 2.7.9 is fairly new.  Current version is 2.7.10.
EDIT2: Confirmed to work on Python 2.7.10

**Comment by tomreece** [comment]
@XVicarious Great information. Would you be willing to tweak the Windows installation instructions in `README.md`? I don't have a Windows box or vm at the moment to test in.

**Comment by XVicarious** [comment]
Sure, I'll try to do it before I go to work tomorrow.

**Comment by tomreece** [comment]
No rush, thanks!

**Comment by tomreece** [comment]
Done in b2063247b9b48bb58736d67ba9731b422f9da298
