### ISSUE TITLE
Combine low value trades to the same user

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#4]
If a single user wants multiple low value cards, accept all of those trades if they exceed a configured threshold.

This would allow you to have low value cards on your Haves list but rest easy knowing that you're sending multiple cards to a single person instead of a 10 cent card with a 50 cent stamp.

Possible problems:
1. What if someone else accepts some of the trades before we have a chance to accept them all? pucauto will need to be a bit faster in this mode.

**Comment by Alchus** [comment]
In abstract, we might be able to avoid committing to an unacceptable portion of a bundle by clicking all of the Send Card buttons at once, then waiting to see how many of them open the confirmation dialog, which reserves the card for 60 seconds. If enough of them succeed that it's still worth sending the bundle, we'd confirm all the trades.

In practice, it might work to have Selenium open several tabs at launch (say, five, but it could be configurable) to the /trades/ page and then only refresh the first one. When we find a bundle, we'll store the trade IDs of each of the cards (It's the href of the fancybox-send in the sendCard button) and dispatch those IDs to each of the other tabs. On each of those tabs, Selenium can run a javascript snippet to modify the href tag of an existing fancybox, then click the button and the confirmation dialog for the card of the injected trade ID will appear. 

Other notes: 

If looking for bundles, it's easier to have the page sorted by member points than by card points. That way we're iterating over each member, instead of each card. Also, if a member has less than our bundle target points available, we know that member and every member below them cannot be a valid recipient.

Lastly, consider the scenario in which our bundle target is 300 points, but a user with only 400points available has matched wants worth 201, 202, and 203 points. There is no legal bundle here, because any single card is under our minimum and the user can't afford two cards. We need to know that before attempting to send any cards, but determining the optimal bundle for a user with constrained points available is the knapsack problem, which is NP-complete. It makes sense to use a quick, if sometimes inaccurate, approximation in such cases. For example: if the user can't afford all the cards we want to send, iteratively recalculate after removing the lowest-value card.

**Comment by tomreece** [comment]
This was requested by Jared T.

**Comment by tomreece** [comment]
Merged in #12. Released in v0.3.0
